FROM node:20-alpine AS build
WORKDIR /usr/src/app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install
COPY frontend ./
RUN npm run build -- --configuration production

FROM nginx:1.25-alpine
COPY --from=build /usr/src/app/dist/tire-test-reporting-platform /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
